### ISSUE TITLE
not able to finish make deps on wheezy( failed on rocksdb)

### ISSUE THREAD

**Issue by MarloweW** [facebook/osquery#1745]
On Debian Wheezy, make deps failed here:

```
/tmp/osquery-provisioning/rocksdb-rocksdb-4.1 /tmp/osquery-provisioning
make[1]: Entering directory `/tmp/osquery-provisioning/rocksdb-rocksdb-4.1'
  GEN      util/build_version.cc
  CC       db/compaction_job.o
db/compaction_job.cc:369:18: error: no member named 'emplace' in 'std::set<rocksdb::Slice, std::function<bool (const
      rocksdb::Slice &, const rocksdb::Slice &)>, std::allocator<rocksdb::Slice> >'
          bounds.emplace(flevel->files[i].smallest_key);
          ~~~~~~ ^
db/compaction_job.cc:370:18: error: no member named 'emplace' in 'std::set<rocksdb::Slice, std::function<bool (const
      rocksdb::Slice &, const rocksdb::Slice &)>, std::allocator<rocksdb::Slice> >'
          bounds.emplace(flevel->files[i].largest_key);
          ~~~~~~ ^
db/compaction_job.cc:375:16: error: no member named 'emplace' in 'std::set<rocksdb::Slice, std::function<bool (const
      rocksdb::Slice &, const rocksdb::Slice &)>, std::allocator<rocksdb::Slice> >'
        bounds.emplace(flevel->files[0].smallest_key);
        ~~~~~~ ^
db/compaction_job.cc:376:16: error: no member named 'emplace' in 'std::set<rocksdb::Slice, std::function<bool (const
      rocksdb::Slice &, const rocksdb::Slice &)>, std::allocator<rocksdb::Slice> >'
        bounds.emplace(flevel->files[num_files - 1].largest_key);
        ~~~~~~ ^
db/compaction_job.cc:383:20: error: no member named 'emplace' in 'std::set<rocksdb::Slice, std::function<bool (const
      rocksdb::Slice &, const rocksdb::Slice &)>, std::allocator<rocksdb::Slice> >'
            bounds.emplace(flevel->files[i].smallest_key);
            ~~~~~~ ^
5 errors generated.
make[1]: *** [db/compaction_job.o] Error 1
make[1]: Leaving directory `/tmp/osquery-provisioning/rocksdb-rocksdb-4.1'
make: *** [deps] Error 2
```

something wrong with gcc version?

**Comment by sharvilshah** [comment]
Yeah, `emplace` is a C++11 feature, and unfortunately the latest gcc version in wheezy packages is stuck on 4.7.2.

GCC 4.8 does have support for `emplace`, but I don't know how much of a pain it is to compile gcc 4.8 on wheezy.

**Comment by theopolis** [comment]
Any interest in working on an install of a newer GCC front end that can compile RocksDB?

**Comment by sharvilshah** [comment]
Yeah, testing out the debian provisioning script with [`install_gcc`](https://github.com/facebook/osquery/blob/master/tools/provision/lib.sh#L10-L70) from `lib.sh`.

(Building gcc and its dependencies and boost takes a while)

Ran into some other errors, but testing things out now. Perhaps we can also do away wheezy specific 
patches to google benchmark too.

**Comment by MarloweW** [comment]
@theopolis  I will try that. However, I am curious about how did you guys make it work on CentOS 6.5?  I remember its gcc version is lower.

**Comment by MarloweW** [comment]
https://github.com/facebook/osquery/blob/master/tools/provision/debian.sh#L54

clang is used instead of gcc in wheezy, why is that?

**Comment by sharvilshah** [comment]
@MarloweW I misspoke in my earlier comment. Clang 3.4 is also missing `emplace` support.
Neither gcc 4.8 nor clang 3.5 exists in wheezy backports :(

CentOS 6.5 is using devtoolset-2 which includes gcc 4.8

**Comment by MarloweW** [comment]
@sharvilshah  get it. I replace clang with gcc 4.8(build via install_gcc mentioned above), thing can goon now.

**Comment by theopolis** [comment]
Awesome, @MarloweW or @sharvilshah if you have a second, would you mind opening a pull request with the changes to `./tools/provision/debian.sh` that set the compilers to GCC before attempting a RocksDB/osquery build?

**Comment by sharvilshah** [comment]
Will do, I already gave it a shot but ran into some issues and haven't had
the time to debug them.

While GCC 4.8.4 and it's dependencies, and in turn rocksdb and osquery
compile/link fine, running it causes it to segfault when acquiring a DB
handle, complains that it cannot find hashtable.h

I will post details when I am near my computer again, but my hunch is that
we need to provide correct LIBRARY_PATH since GCC 4.8.4 is installed in a
non-standard location (/opt).

**Comment by theopolis** [comment]
Ah, in the top most CMakeLists there is a list of distribution names that should link their C++ implementation statically. We'll need to do that here too. The alternative is adding logic to write RPATHs or absolute path linking for this specific lib.
