### ISSUE TITLE
gflags fails to build on fresh ubuntu14 box

### ISSUE THREAD

**Issue by sharvilshah** [facebook/osquery#1428]
gflags fails to build on vanilla ubuntu14 box on vagrant/virtualbox.

```
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/g++
Build flags: -fPIE;-fPIC;-O2;-DNDEBUG;-march=x86-64;-mtune=i386;-mno-avx
Id flags:

The output was:
1
CMakeCXXCompilerId.cpp:1:0: error: CPU you selected does not support x86-64 instruction set
 /* This source file must have a .cpp extension so that all C++ compilers
 ^


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/g++
Build flags: -fPIE;-fPIC;-O2;-DNDEBUG;-march=x86-64;-mtune=i386;-mno-avx
Id flags: -c

The output was:
1
CMakeCXXCompilerId.cpp:1:0: error: CPU you selected does not support x86-64 instruction set
```

I did upgrade Vagrant and VirtualBox to the latest releases. VirtualBox 5.0 does support avx instructions, but that shouldn't matter since we have `-mno-avx`

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ cat /proc/cpuinfo | grep flags
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx rdrand lahf_lm abm avx2
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx rdrand lahf_lm abm avx2
```

It does build fine on the centos7.1 box. I did destroy the ubuntu14 box and started again with fresh box but not much help.

**Comment by sharvilshah** [comment]
Same problem with ubuntu12 box.
And this may not be vagrant/virtualbox related. Spun up an ubuntu14 instance on digitalocean and same errors.

**Comment by sharvilshah** [comment]
My gcc version on centos7 is 4.8.3 and on ubuntu14 is 4.8.4

Compiles and works after setting  `-mtune=generic` (which according to gcc docs is equivalent to i686) at these places: https://github.com/facebook/osquery/pull/1401/files#diff-597ce87af9a8336c63c5326355a5f25bR12 and https://github.com/facebook/osquery/pull/1401/files#diff-af3b638bc2a3e6c650974192a53c7291R152

I am going to wait on the PR since I don't know what side effects that change might have.
