### ISSUE TITLE
Link error on Ubuntu 14.04

### ISSUE THREAD

**Issue by astanway** [facebook/osquery#212]
> `sudo make deps && sudo make install`

[ 68%] Building CXX object osquery/CMakeFiles/daemon.dir/main/daemon.cpp.o
Linking CXX executable osqueryd
/usr/local/lib/librocksdb.a(format.o): In function `rocksdb::port::Zlib_Uncompress(char const*, unsigned long, int*, int)':
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:255: undefined reference to`inflateInit2_'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:278: undefined reference to `inflate'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:300: undefined reference to`inflateEnd'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:306: undefined reference to `inflateEnd'
/usr/local/lib/librocksdb.a(format.o): In function`rocksdb::port::BZip2_Uncompress(char const_, unsigned long, int_)':
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:375: undefined reference to `BZ2_bzDecompressInit'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:394: undefined reference to`BZ2_bzDecompress'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:413: undefined reference to `BZ2_bzDecompressEnd'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:419: undefined reference to`BZ2_bzDecompressEnd'
/usr/local/lib/librocksdb.a(block_based_table_builder.o): In function `rocksdb::port::Zlib_Compress(rocksdb::CompressionOptions const&, char const*, unsigned long, std::string*)':
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:195: undefined reference to`deflateInit2_'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:216: undefined reference to `deflate'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:240: undefined reference to`deflateEnd'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:234: undefined reference to `deflateEnd'
/usr/local/lib/librocksdb.a(block_based_table_builder.o): In function`rocksdb::port::BZip2_Compress(rocksdb::CompressionOptions const&, char const_, unsigned long, std::string_)':
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:322: undefined reference to `BZ2_bzCompressInit'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:341: undefined reference to`BZ2_bzCompress'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:363: undefined reference to `BZ2_bzCompressEnd'
/home/ubuntu/osquery/.sources/rocksdb-rocksdb-3.5/./port/port_posix.h:357: undefined reference to`BZ2_bzCompressEnd'

Git bisect shows it breaks on https://github.com/facebook/osquery/commit/99f5052d15b75f4c0e5a7361c1f2f37e01cef7d1
