### ISSUE TITLE
Build failure with boost 1.66.0

### ISSUE THREAD

**Issue by fxcoudert** [facebook/osquery#4009]
osquery 2.10.2 fails to build with Boost 1.66.0 on macOS 10.12 and 10.13 (which we uncovered as part of testing for Homebrew):

```
In file included from /tmp/osquery-20171219-55659-ur9r4b/generated/gen-cpp/Extension.cpp:7:
/tmp/osquery-20171219-55659-ur9r4b/generated/gen-cpp/Extension.h:419:72: error: virtual function 'getProcessor' has a different return type ('::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor>') than the function it overrides (which has return type 'boost::shared_ptr<TProcessor>')
  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/private/tmp/osquery-20171219-55659-ur9r4b/brew_vendor/thrift/include/thrift/TProcessor.h:215:41: note: overridden virtual function is here
  virtual boost::shared_ptr<TProcessor> getProcessor(const TConnectionInfo& connInfo) = 0;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/tmp/osquery-20171219-55659-ur9r4b/generated/gen-cpp/Extension.cpp:914:58: error: no matching constructor for initialization of '::apache::thrift::ReleaseHandler<ExtensionIfFactory>'
  ::apache::thrift::ReleaseHandler< ExtensionIfFactory > cleanup(handlerFactory_);
                                                         ^       ~~~~~~~~~~~~~~~
/private/tmp/osquery-20171219-55659-ur9r4b/brew_vendor/thrift/include/thrift/TProcessor.h:178:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from '::apache::thrift::stdcxx::shared_ptr<ExtensionIfFactory>' to 'apache::thrift::ReleaseHandler<osquery::extensions::ExtensionIfFactory>' for 1st argument
class ReleaseHandler {
      ^
/private/tmp/osquery-20171219-55659-ur9r4b/brew_vendor/thrift/include/thrift/TProcessor.h:178:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from '::apache::thrift::stdcxx::shared_ptr<ExtensionIfFactory>' to 'const apache::thrift::ReleaseHandler<osquery::extensions::ExtensionIfFactory>' for 1st argument
/private/tmp/osquery-20171219-55659-ur9r4b/brew_vendor/thrift/include/thrift/TProcessor.h:180:3: note: candidate constructor not viable: no known conversion from '::apache::thrift::stdcxx::shared_ptr<ExtensionIfFactory>' to 'const boost::shared_ptr<ExtensionIfFactory>' for 1st argument
  ReleaseHandler(const boost::shared_ptr<HandlerFactory_>& handlerFactory)
  ^
2 errors generated.
```

**Comment by ilovezfs** [comment]
CC @theopolis

**Comment by theopolis** [comment]
@ilovezfs, if you try to build osquery from `master` right now, using the `boost` and `thrift` from Homebrew (don't vendor them in), does it work?

I've updated our Thrift API usage to 0.11, from 0.10, it seems they are using `std::shared_ptr` now which is fantastic. I'm sure there is a way to compile and prefer `boost::shared_ptr` but I'm not interested in keeping backward compatibility and will resolve on other platforms (like FreeBSD, which is still on Thrift 0.9.3).

I also changed our `beast` API usage to be (I think) compatibility with what's in Boost 1.66. We have not updated to use the newest Boost since it will require new Windows nupkgs.

If you're build does not work then I will investigate getting us to build on the newest Boost too.

**Comment by theopolis** [comment]
Ah, nvm, this doesn't seem possible yet. I'll have to fragment our `boost` dependencies like I've done with `thrift`. Linux and macOS will build with 1.66 shortly.

**Comment by theopolis** [comment]
Ok now try!

**Comment by ilovezfs** [comment]
@theopolis awesome! I'll try to build master now.

**Comment by ilovezfs** [comment]
@theopolis LGTM:
```
==> Summary
🍺  /usr/local/Cellar/osquery/HEAD-489ec3f_1: 80 files, 21.1MB, built in 10 minutes 19 seconds
bash-3.2$ brew test -vd osquery
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/osquery.rb
Testing osquery
/usr/bin/sandbox-exec -f /tmp/homebrew20171223-74912-1db7bfk.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/osquery.rb -vd --HEAD
/usr/local/Homebrew/Library/Homebrew/test.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/osquery.rb
==> /usr/local/Cellar/osquery/HEAD-489ec3f_1/bin/osqueryi -L
bash-3.2$ brew linkage osquery
System libraries:
  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
  /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
  /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
  /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
  /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
  /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
  /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
  /System/Library/Frameworks/Security.framework/Versions/A/Security
  /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
  /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
  /usr/lib/libSystem.B.dylib
  /usr/lib/libbsm.0.dylib
  /usr/lib/libbz2.1.0.dylib
  /usr/lib/libc++.1.dylib
  /usr/lib/libcups.2.dylib
  /usr/lib/libiconv.2.dylib
  /usr/lib/libobjc.A.dylib
  /usr/lib/libresolv.9.dylib
  /usr/lib/libxar.1.dylib
  /usr/lib/libxml2.2.dylib
  /usr/lib/libz.1.dylib
Homebrew libraries:
  /usr/local/opt/augeas/lib/libaugeas.0.dylib (augeas)
  /usr/local/opt/augeas/lib/libfa.1.dylib (augeas)
  /usr/local/opt/boost/lib/libboost_context-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_regex-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_system-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_thread-mt.dylib (boost)
  /usr/local/opt/gflags/lib/libgflags.2.2.dylib (gflags)
  /usr/local/opt/glog/lib/libglog.0.3.5.dylib (glog)
  /usr/local/opt/libarchive/lib/libarchive.13.dylib (libarchive)
  /usr/local/opt/libmagic/lib/libmagic.1.dylib (libmagic)
  /usr/local/opt/librdkafka/lib/librdkafka.1.dylib (librdkafka)
  /usr/local/opt/lldpd/lib/liblldpctl.4.dylib (lldpd)
  /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (openssl)
  /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (openssl)
  /usr/local/opt/rocksdb/lib/librocksdb_lite.5.8.dylib (rocksdb)
  /usr/local/opt/sleuthkit/lib/libtsk.13.dylib (sleuthkit)
  /usr/local/opt/thrift/lib/libthrift-0.11.0.dylib (thrift)
  /usr/local/opt/xz/lib/liblzma.5.dylib (xz)
  /usr/local/opt/yara/lib/libyara.3.dylib (yara)
  /usr/local/opt/zstd/lib/libzstd.1.dylib (zstd)
Dependencies with no linkage:
  asio
  rapidjson
bash-3.2$ brew linkage --reverse osquery
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
  bin/osqueryd
  bin/osqueryi

/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
  bin/osqueryd
  bin/osqueryi

/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
  bin/osqueryd
  bin/osqueryi

/System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
  bin/osqueryd
  bin/osqueryi

/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
  bin/osqueryd
  bin/osqueryi

/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
  bin/osqueryd
  bin/osqueryi

/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
  bin/osqueryd
  bin/osqueryi

/System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
  bin/osqueryd
  bin/osqueryi

/System/Library/Frameworks/Security.framework/Versions/A/Security
  bin/osqueryd
  bin/osqueryi

/System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
  bin/osqueryd
  bin/osqueryi

/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
  bin/osqueryd
  bin/osqueryi

/usr/lib/libSystem.B.dylib
  bin/osqueryd
  bin/osqueryi

/usr/lib/libbsm.0.dylib
  bin/osqueryd
  bin/osqueryi

/usr/lib/libbz2.1.0.dylib
  bin/osqueryd
  bin/osqueryi

/usr/lib/libc++.1.dylib
  bin/osqueryd
  bin/osqueryi

/usr/lib/libcups.2.dylib
  bin/osqueryd
  bin/osqueryi

/usr/lib/libiconv.2.dylib
  bin/osqueryd
  bin/osqueryi

/usr/lib/libobjc.A.dylib
  bin/osqueryd
  bin/osqueryi

/usr/lib/libresolv.9.dylib
  bin/osqueryd
  bin/osqueryi

/usr/lib/libxar.1.dylib
  bin/osqueryd
  bin/osqueryi

/usr/lib/libxml2.2.dylib
  bin/osqueryd
  bin/osqueryi

/usr/lib/libz.1.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/augeas/lib/libaugeas.0.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/augeas/lib/libfa.1.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/boost/lib/libboost_context-mt.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/boost/lib/libboost_filesystem-mt.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/boost/lib/libboost_regex-mt.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/boost/lib/libboost_system-mt.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/boost/lib/libboost_thread-mt.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/gflags/lib/libgflags.2.2.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/glog/lib/libglog.0.3.5.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/libarchive/lib/libarchive.13.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/libmagic/lib/libmagic.1.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/librdkafka/lib/librdkafka.1.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/lldpd/lib/liblldpctl.4.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/rocksdb/lib/librocksdb_lite.5.8.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/sleuthkit/lib/libtsk.13.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/thrift/lib/libthrift-0.11.0.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/xz/lib/liblzma.5.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/yara/lib/libyara.3.dylib
  bin/osqueryd
  bin/osqueryi

/usr/local/opt/zstd/lib/libzstd.1.dylib
  bin/osqueryd
  bin/osqueryi
bash-3.2$ mdutil -t /usr/local/opt/boost
/usr/local/Cellar/boost/1.66.0
bash-3.2$
```

**Comment by theopolis** [comment]
Tagged 2.11.1 https://github.com/facebook/osquery/releases/tag/2.11.1

**Comment by ilovezfs** [comment]
Thanks @theopolis! Homebrew PR for 2.11.1: https://github.com/Homebrew/homebrew-core/pull/22090
