### PR TITLE
[Fix #1578] Support OPENSSL_NO_SSV3

### LINKED ISSUE #1578: Build from source fails on OS X 10.11
With [libressl 2.3.0 release](http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.3.0-relnotes.txt), they have removed SSLv3 code, which I think is the result of build failures on OS X 10.11

```
-- Found OpenSSL: /usr/local/opt/libressl/lib/libssl.a;/usr/local/opt/libressl/lib/libcrypto.a (found version "2.0.0")
-- Looking for TLSv1_2_client_method in /usr/local/opt/libressl/lib/libssl.a
-- Looking for TLSv1_2_client_method in /usr/local/opt/libressl/lib/libssl.a - found
-- Looking for TLSv1_1_client_method in /usr/local/opt/libressl/lib/libssl.a
-- Looking for TLSv1_1_client_method in /usr/local/opt/libressl/lib/libssl.a - found
-- Looking for TLSv1_client_method in /usr/local/opt/libressl/lib/libssl.a
-- Looking for TLSv1_client_method in /usr/local/opt/libressl/lib/libssl.a - found

[ 54%] Building CXX object osquery/config/CMakeFiles/osquery_config_plugins.dir/plugins/tls.cpp.o
In file included from /Users/test/osquery/osquery/config/plugins/tls.cpp:24:
In file included from /Users/test/osquery/osquery/remote/utility.h:17:
In file included from /Users/test/osquery/osquery/remote/transports/tls.h:20:
In file included from /usr/local/include/boost/network/protocol/http/client.hpp:26:
In file included from /usr/local/include/boost/network/protocol/http/client/facade.hpp:12:
In file included from /usr/local/include/boost/network/protocol/http/client/pimpl.hpp:16:
In file included from /usr/local/include/boost/network/protocol/http/traits/connection_policy.hpp:11:
In file included from /usr/local/include/boost/network/protocol/http/policies/simple_connection.hpp:20:
In file included from /usr/local/include/boost/network/protocol/http/client/connection/sync_base.hpp:22:
In file included from /usr/local/include/boost/network/protocol/http/client/connection/sync_ssl.hpp:11:
In file included from /usr/local/include/boost/asio/ssl.hpp:19:
In file included from /usr/local/include/boost/asio/ssl/context.hpp:786:
/usr/local/include/boost/asio/ssl/impl/context.ipp:93:31: error: no member named 'SSLv3_method' in the global namespace; did you mean 'SSLv23_method'?
    handle_ = ::SSL_CTX_new(::SSLv3_method());
                            ~~^
/usr/local/opt/libressl/include/openssl/ssl.h:1677:19: note: 'SSLv23_method' declared here
const SSL_METHOD *SSLv23_method(void);          /* SSLv3 or TLSv1.* */
                  ^
```

Bottled install from homebrew works, which links against brew provided openssl (not sure how):

```
tests-Mac:~ test$ otool -LV /usr/local/bin/osqueryi
/usr/local/bin/osqueryi:
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	time stamp 2 Wed Dec 31 16:00:02 1969
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	time stamp 2 Wed Dec 31 16:00:02 1969
```

And `.pkg` install works too since that links against Apple provided `/usr/lib/libssl.dylib`

I am still investigating this, will update with details. If anyone has thoughts would love to hear them.

### PR DESCRIPTION
**Pull request by theopolis**
1. Check for SSLv3 methods in the OpenSSL static library implementation.
2. If SSLv3 methods are not included, add basic declarations for Boost's ASIO library.
3. Since we are removing support for SSLv3 explicitly using `OPENSSL_NO_SSLV3`, and since ASIO does not respect this feature selection, we must add no-op symbols for several SSLv3 methods.

### CODE REVIEW

**Comment by theopolis** [comment]
This is required to build on OS X as of LibreSSL 2.3.0: https://github.com/Homebrew/homebrew/commit/aec2142aa3f1a2d9bc376c931253dc5f8a25a709

**Comment by osqueryer** [comment]
Build is good! :+1:

**Comment by theopolis** [comment]
Since we're building on 10.10 within Jenkins and using that output package we do not need to also required a minimum ABI build/link line. When installing binary sources from Homebrew, using a non-native minimum ABI requirement for osquery's linking produces LOTS of warnings. 

In the case where these are not harmless the CI build on 10.10 and 10.9 will fail.

**Comment by osqueryer** [comment]
Build is good! :+1:

**Comment by sharvilshah** [comment]
Beat me to it :)

Thanks, this looks good.  And compiles on 10.11 and with `BUILD_USE_LIBRESSL` env variable on 10.10. 

Also I didn't realize that SSLv3 methods returned `SSL_METHOD*` and not `SSL_CTX*` like the TLS 1.1 and 1.2 ones.

**Comment by sharvilshah** [comment]
Spoke a little too soon, linker errors:

```
Undefined symbols for architecture x86_64:
  "_SSLv2_client_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in libcppnetlib-client-connections.a(client.cpp.o)
  "_SSLv2_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in libcppnetlib-client-connections.a(client.cpp.o)
  "_SSLv2_server_method", referenced from:
      boost::asio::ssl::context::context(boost::asio::ssl::context_base::method) in libcppnetlib-client-connections.a(client.cpp.o)
ld: symbol(s) not found for architecture x86_64
```

Do you think we still need to define `OPENSSL_NO_SSL2`?

**Comment by theopolis** [comment]
Excellent catch! I meant to move those feature defines to the top of `tls.h`.

**Comment by osqueryer** [comment]
Build failed :-1:

**Comment by osqueryer** [comment]
Build failed :-1:

**Comment by osqueryer** [comment]
Build is good! :+1:
