### ISSUE TITLE
SNI support for TLS plugin

### ISSUE THREAD

**Issue by defunctzombie** [facebook/osquery#1746]
I've been trying rather unsuccessfully to get the osquery TLS plugin to communicate to a server deployed behind a load balancer which handles several domains via ssl. From what I can tell after trying various ways to connect and googling around it might be an SNI issue. Documentation on the specific http library used in osquery was a bit sparse on the topic so I am posting here to see if any of the maintainers or collaborators have run into a similar issue or may know how to enable SNI in the boost network library being used.

**Comment by defunctzombie** [comment]
Closing because I am not 100% the issue is/was SNI related and not some other stricter SSL configuration or other certificate issue which caused the TLS connection to error.

**Comment by theopolis** [comment]
Glad to hear the issue *might* be resolved. ;) I can definitely help dig through the boost ASIO library to find where/if SNI exists if needed, just let me know.

**Comment by defunctzombie** [comment]
The issue here seemed to happen when I deployed an osquery TLS endpoint on heroku but behind cloudflare to leverage their free HTTPS support. I was able to get osquery to talk to the heroku endpoint on a heroku provided subdomain domain (with ssl) but when trying to use osquery to talk to the cloudflare domain it would general a TLS error and never connect. Interestingly enough trying to use `openssl s_client` to connect to same said cloudflare domain also doesn't work for me. I suspect it is either due to cloudflare security settings or how they have configured their ssl certs but bundling many domains into a single cert.

**Comment by readshaw** [comment]
I think I might be encountering a similar issue with osquery client trying to connect to an AWS API Gateway (which seems to use API CloudFront).  I am getting TLS 1.2 handshake failures, though the client hello is offering ciphers which overlap with the ciphers offered by the server, such as ECDHE-RSA-AES128-GCM-SHA256 and ECDHE-RSA-AES256-GCM-SHA384.

Has anybody had similar experiences?

**Comment by readshaw** [comment]
@theopolis I'd be interesting in knowing how SNI support could be added.  It's blocking the deployment scenario with AWS API Gateway/CloudFront I mention above.

**Comment by theopolis** [comment]
Ok let me take a look, if it's blocking you I'll get support in ASAP. I'm guessing I can test/repo on a normal / common SNI-required setup? I'll try, and if that's the case, and the TLS client fails, it should be easy to investigate a fix.

**Comment by defunctzombie** [comment]
@theopolis easy way you should be able to test is with a free cloudflare
account and some domain you can change DNS on. You can point your domain
name servers to cloudflare and then point osquery to that.

**Comment by readshaw** [comment]
Thanks - that would be great.  

I believe that when it boils down to the OpenSSL code to call, it will look something like:

SSL_set_tlsext_host_name(<ssl-context>, "<hostname>");

I'm just not sure how to get to the context object that must be down in the bowels of Boost.

I couldn't see anywhere in the Boost source where TLS extension functions were being called.

As far as testing goes, if the TLS extension for SNI is specified for a server that doesn't use SNI, it should still connect.  Here's an example:

$ openssl s_client -showcerts -tls1_2 -connect www.facebook.com:443 -servername ignorethis

Will still connect and complete the SSL handshake.

I've seen other packages always supply this tlsext extension to match the hostname being connected to.

**Comment by theopolis** [comment]
Perfect, that's awesome! Worst case we'll need to modify cpp-netlib to grab the context or extend the API to add an SNI enabling call.

**Comment by theopolis** [comment]
Bad news is, I there's no API to retrieve the `asio::ssl::context` from cpp-netlib. But if there were, once could access the OpenSSL native context implementation through: http://www.boost.org/doc/libs/1_55_0/doc/html/boost_asio/reference/ssl__context/native_handle.html. cpp-netlib's client APIs are PIMPL so it'd mean an anti-pattern (+ a bit of refactoring) to expose the context object. The best option is to add an additional client option that communicates the SNI hostname, similar to the options members for setting certificate bundle/methods/etc.

It will take a bit of scaffolding to add this change locally, and begin building/linking against a local checkout of cpp-netlib. We've done this before while waiting for version 0.11, so I understand the needed parts. But I want to quickly explore other HTTP/TLS client implementations.

**Comment by theopolis** [comment]
No support (or rather, use of `SSL_set_tlsext_host_name`) within Thrift's SSL/TLS [implementation](https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/transport/TSSLSocket.cpp) either.

**Comment by readshaw** [comment]
Kinda surprising for how prevalent SNI is becoming with *-as-a-Service

**Comment by theopolis** [comment]
So, testing using:
```cpp
SSL_CTX_ctrl(context_.native_handle(), SSL_CTRL_SET_TLSEXT_HOSTNAME,
    TLSEXT_NAMETYPE_host_name,
    const_cast<char*>(sni_hostname->c_str()));
```

I sort of made that up, all examples apply the CTRL to the `SSL` object, not the `SSL_CTX` object. This doesn't work :/

**Comment by theopolis** [comment]
For those blocked by needing SNI support, there's a PR up to cpp-netlib: https://github.com/cpp-netlib/cpp-netlib/pull/602, if that or the other PR into their `0.12-devel` branch lands I will extend osquery's #1856 to include a CMake target to install the cpp-netlib master.

@readshaw, @defunctzombie, are you building osquery yourself or using the published binaries?

**Comment by readshaw** [comment]
Thanks Teddy - really appreciate your interest in this enhancement.

I'm building my own binaries so I can include my distribute my own
configuration file.  I am not tailoring any of the C++ code.

**Comment by theopolis** [comment]
When #1856 is merged we'll have a compile-time check for cpp-netlib's TLS SNI support. To build osquery with SNI support:

- Install cpp-netlib from the `0.12-devel` branch. While it's also possible to install from their master, I have not tested this with osquery.
```
git clone https://github.com/cpp-netlib/cpp-netlib.git
cd cpp-netlib
git checkout 0.12-devel
./build.sh
cd build
sudo make install
```
- Build osquery from our master on the same machine!

**Comment by readshaw** [comment]
I've pulled the latest cpp-netlib and osquery code and am trying to build with the SNI support you've implemented.  After cleaning up old version of cpp-netlib and getting my pre-reqs right, I am now at the point where I'm getting linker issues towards the end of the osquery compilation.

```
[100%] Linking CXX executable osquery_additional_tests
Undefined symbols for architecture x86_64:
  "boost::network::http::impl::ssl_delegate::~ssl_delegate()", referenced from:
      std::__1::__shared_ptr_emplace<boost::network::http::impl::ssl_delegate, std::__1::allocator<boost::network::http::impl::ssl_delegate> >::~__shared_ptr_emplace() in libosquery_additional.a(tls.cpp.o)
      std::__1::__shared_ptr_emplace<boost::network::http::impl::ssl_delegate, std::__1::allocator<boost::network::http::impl::ssl_delegate> >::~__shared_ptr_emplace() in libosquery_additional.a(tls.cpp.o)
  "boost::network::http::impl::ssl_delegate::ssl_delegate(asio::io_service&, bool, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, long)", referenced from:
      std::__1::shared_ptr<boost::network::http::impl::ssl_delegate> std::__1::shared_ptr<boost::network::http::impl::ssl_delegate>::make_shared<asio::io_service&, bool&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&, long&>(asio::io_service&&&, bool&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >&&&, long&&&) in libosquery_additional.a(tls.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any thoughts on what I could try next?

**Comment by theopolis** [comment]
Oh man, not sure about that one. Could you provide some more details about your build environment?  Some immediate (but not exhaustive) questions:
- What version of boost is installed, and where does it come from?
- Where did cpp-netlib install too, and are you sure there's not a second installed by the OS/package manager?
- Was the `./build/PLATFORM` directory removed from the osquery perspective, aka a `make clean`?

Building with a `make -j4 VERBOSE=1` will show the exact linker command, that would be helpful too. :+1:

**Comment by readshaw** [comment]
boost-1.60.0_1 is installed, via brew.

With cpp-netlib, I uninstalled the package I had installed via brew and
built and installed from the master branch.  I think you said that your
change was in 0.12 and master.

Here's the build output from the failing linker step:


cd /Users/nreadshaw/git/osquery/build/darwin/osquery &&
/usr/local/Cellar/cmake/3.4.3/bin/cmake -E cmake_link_script
CMakeFiles/osquery_additional_tests.dir/link.txt --verbose=1

/usr/bin/clang++    -isysroot
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
-Wl,-search_paths_first -Wl,-headerpad_max_install_names
CMakeFiles/osquery_additional_tests.dir/main/tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/config/tests/packs_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/config/parsers/tests/events_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/config/parsers/tests/file_paths_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/config/parsers/tests/options_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/devtools/tests/printer_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/dispatcher/tests/scheduler_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/distributed/tests/distributed_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/events/darwin/tests/fsevents_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/logger/plugins/tests/filesystem_logger_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/logger/plugins/tests/tls_logger_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/remote/tests/requests_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/remote/enroll/tests/enroll_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/remote/serializers/tests/json_serializers_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/remote/transports/tests/tls_transports_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/sql/tests/sql_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/sql/tests/sqlite_util_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/sql/tests/virtual_table_tests.cpp.o
CMakeFiles/osquery_additional_tests.dir/tables/other/tests/yara_tests.cpp.o
-o osquery_additional_tests  -L/usr/local/lib  -Wl,-force_load libosquery.a
-Wl,-force_load libosquery_additional.a
../third-party/gtest-1.7.0/libgtest.a libosquery_testing.a
/usr/local/lib/librocksdb_lite.a /usr/local/lib/libsnappy.a
/usr/local/lib/libthrift.a ../third-party/glog/lib/libglog.a
/usr/local/lib/libgflags.dylib /usr/local/opt/libressl/lib/libcrypto.a
/usr/local/opt/libressl/lib/libssl.a /usr/lib/libreadline.dylib
/opt/local/lib/libncurses.dylib -lpthread -lbz2 -lz -ldl -rdynamic
-Wl,-dead_strip -mmacosx-version-min=10.11
/usr/local/lib/libboost_thread-mt.a /usr/local/lib/liblz4.a
/usr/local/lib/libboost_system.a /usr/local/lib/libboost_filesystem.a
/usr/local/lib/libboost_regex.a /usr/local/lib/libyara.a -framework
Foundation /usr/local/lib/libcppnetlib-uri.a
/usr/local/lib/libcppnetlib-client-connections.a -framework CoreServices
-framework SystemConfiguration -framework IOKit -framework DiskArbitration
-framework CoreFoundation -framework Security -framework OpenDirectory
-framework DiskArbitration -framework CoreFoundation -framework Security
-framework OpenDirectory /usr/lib/libresolv.dylib /usr/lib/libarchive.dylib
/usr/local/lib/libmagic.a /usr/local/lib/libtsk.a

Undefined symbols for architecture x86_64:

  "boost::network::http::impl::ssl_delegate::~ssl_delegate()", referenced
from:


std::__1::__shared_ptr_emplace<boost::network::http::impl::ssl_delegate,
std::__1::allocator<boost::network::http::impl::ssl_delegate>
>::~__shared_ptr_emplace() in libosquery_additional.a(tls.cpp.o)


std::__1::__shared_ptr_emplace<boost::network::http::impl::ssl_delegate,
std::__1::allocator<boost::network::http::impl::ssl_delegate>
>::~__shared_ptr_emplace() in libosquery_additional.a(tls.cpp.o)


"boost::network::http::impl::ssl_delegate::ssl_delegate(asio::io_service&,
bool, boost::optional<std::__1::basic_string<char,
std::__1::char_traits<char>, std::__1::allocator<char> > >,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char,
std::__1::char_traits<char>, std::__1::allocator<char> > >,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >, boost::optional<std::__1::basic_string<char,
std::__1::char_traits<char>, std::__1::allocator<char> > >,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >, long)", referenced from:

      std::__1::shared_ptr<boost::network::http::impl::ssl_delegate>
std::__1::shared_ptr<boost::network::http::impl::ssl_delegate>::make_shared<asio::io_service&,
bool&, boost::optional<std::__1::basic_string<char,
std::__1::char_traits<char>, std::__1::allocator<char> > >&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&, long&>(asio::io_service&&&, bool&&&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&&&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&&&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&&&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&&&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&&&,
boost::optional<std::__1::basic_string<char, std::__1::char_traits<char>,
std::__1::allocator<char> > >&&&, long&&&) in
libosquery_additional.a(tls.cpp.o)

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see
invocation)

make[3]: *** [osquery/osquery_additional_tests] Error 1

make[2]: *** [osquery/CMakeFiles/osquery_additional_tests.dir/all] Error 2

make[1]: *** [all] Error 2

make: *** [all] Error 2

**Comment by theopolis** [comment]
Ok, let me attempt to replicate on OS X. I'll ping back tomorrow morning!

**Comment by readshaw** [comment]
Thanks Teddy.

**Comment by readshaw** [comment]
An update but still no success.

I went back to the older cpp-netlib server (0.11) and confirmed that I could build osquery correctly from master branch of osquery.  Still using boost-1.60.0_1, installed via brew.

I then removed cpp-netlib 0.11 brew package and confirmed there were no remnants under /usr/local.  I used my locally built cpp-netlib cloned from master branch at https://github.com/cpp-netlib/cpp-netlib.git and installed it per Teddy's instructions above.

It feels like an incompatibility between the built cpp-netlib and boost.  Then next thing I will try is to clone and built the 0.11 branch of cpp-netlib locally and install on my system to try and separate a build environment issue with cpp-netlib from a cpp-netlib code version issue.

**Comment by theopolis** [comment]
I tried with .60 and it worked with the 0.12-devel branch. I'm trying to repro the missing-deconstructor issue. You could also try building/installing cpp-netlib from master.

**Comment by readshaw** [comment]
Are you using a brew package for boost 1.60 or building from source?  I am using the brew package. 

I did try building cpp-netlib from 0.12-devel and master and the linker errors were the same.  

Thanks again for your suggestions. 

Cheers,
Neil

**Comment by readshaw** [comment]
OK, I'm making progress now.

I needed an extra flag when building cpp-netlib, as follows:

```
git clone https://github.com/cpp-netlib/cpp-netlib.git
cd cpp-netlib
git checkout 0.12-devel
ENABLE_HTTPS=ON ./build.sh
cd build
sudo make install
```

This also used a brewed openssl instead of the native OS/X OpenSSL, which version < 1.0.

cpp-netlib is now building with SSL support, as is osqueryd.  Now back to testing SNI!

**Comment by theopolis** [comment]
Oh wow, excellent find. I've just been slipstreaming the tgz into our provision scripts, which export those defines on the shell rather opaquely. 

Meanwhile, I've tried to add SNI to Thrift: https://github.com/apache/thrift/commit/937228e030569bf25ceb379c9491426709792701

Perhaps we can try moving to pure thrift for our APIs? Right now we use thrift for domain socket based extensions APIs and cpp-netlib for our TLS plugins.

**Comment by readshaw** [comment]
The more SNI support the better.  It's so commonplace now with shared,
hosted environments that this is a limitation that would be good to remove.

I don't know enough about Thrift to compare/contract with cpp-netlib.  I
think cpp-netlib was easy enough to build once I got the dependencies and
cmake flags correct, but that could probably be said about any open source
package.
