### ISSUE TITLE
OS X 10.10 Yosemite build fails with Boost 1.64.0 

### ISSUE THREAD

**Issue by ilovezfs** [facebook/osquery#3186]
Note that the build with Boost 1.64.0 is fine on 10.11 and 10.12.

Here's the build log for a local build deparallelized: https://gist.github.com/ilovezfs/b6519051c5a9015c4ea9bbadbaa7c0dd
Here's the log for 10.10 from Homebrew CI: https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/301/version=yosemite/console

The error is
```
/usr/local/include/boost/fiber/detail/spinlock_ttas.hpp:88:24: error: thread-local storage is not supported for the current target
                static thread_local std::minstd_rand generator;
                       ^
```

CC @theopolis

**Comment by theopolis** [comment]
I guess we'll have to turn off build support for `10.10` RIP.

**Comment by ilovezfs** [comment]
:+1:

**Comment by theopolis** [comment]
So the underlying issue here was `thread_local` not being available on `10.10`. That's interesting as `10.12` should have the same issue because I don't think `thread_local` is available to `clang` on any Apple OS.

But the `boost` formula: https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost.rb has no special notes or compile options to avoid their use of `thread_local`.

**Comment by ilovezfs** [comment]
I think it's available as of >=10.11 if you have Xcode >= 8.

**Comment by theopolis** [comment]
I'm going to call this closed/wont-fix as we're now restricted to 10.12: #3383
