### PR TITLE
[Fix #1782] Disable Variadic Templates with Boost

### LINKED ISSUE #1782: Breaking changes with Boost 1.60.0
It seems boost 1.60.0 has some breaking changes (might be related to #1781)
Can't build on OS X 10.11 with Apple LLVM version 7.0.2 (clang-700.1.81).

A quick search through Boost's Trac didn't reveal any related bugs, I'll try searching their mailing list.
Builds fine with boost 1.59.0

```
In file included from /usr/local/include/boost/thread/shared_mutex.hpp:22:
In file included from /usr/local/include/boost/thread/pthread/shared_mutex.hpp:13:
In file included from /usr/local/include/boost/thread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/pthread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/lock_types.hpp:22:
In file included from /usr/local/include/boost/chrono/time_point.hpp:33:
In file included from /usr/local/include/boost/chrono/duration.hpp:42:
In file included from /usr/local/include/boost/type_traits/common_type.hpp:21:
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:28:5: warning: declaration does not declare anything [-Wmissing-declarations]
    static boost::true_type check(int);
    ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:31:5: warning: declaration does not declare anything [-Wmissing-declarations]
    static boost::false_type check(...);
    ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:33:27: error: use of undeclared identifier 'check'
    using type = decltype(check<F>(0));
                          ^
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:33:33: error: cannot refer to class template 'F' without a template argument list
    using type = decltype(check<F>(0));
                                ^
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:24:35: note: template is declared here
template<template<class...> class F, class... T>
                                  ^
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:37:1: error: no type named 'type' in 'boost::type_traits_detail::mp_valid_impl<common_type_fold, long long, long long, long>'
using mp_valid = typename mp_valid_impl<F, T...>::type;
^~~~~
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:50:95: note: in instantiation of template type alias 'mp_valid' requested here
template<template<class...> class F, class... T> using mp_defer = typename boost::conditional<mp_valid<F, T...>::value, mp_defer_impl<F, T...>, mp_empty>::type;
                                                                                              ^
/usr/local/include/boost/type_traits/common_type.hpp:47:55: note: in instantiation of template type alias 'mp_defer' requested here
struct common_type<T1, T2, T...>: type_traits_detail::mp_defer<type_traits_detail::common_type_fold, T1, T2, T...>
                                                      ^
/usr/local/include/boost/chrono/duration.hpp:253:30: note: in instantiation of template class 'boost::common_type<long long, long long, long>' requested here
            typedef typename common_type<
                             ^
/usr/local/include/boost/chrono/duration.hpp:315:20: note: in instantiation of member function 'boost::chrono::detail::duration_cast_aux<boost::chrono::duration<long long, boost::ratio<1, 1000000000> >, boost::chrono::duration<long
      long, boost::ratio<1, 1> >, boost::ratio<1, 1000000000>, true, false>::operator()' requested here
            return Aux()(fd);
                   ^
/usr/local/include/boost/chrono/duration.hpp:788:16: note: in instantiation of member function 'boost::chrono::detail::duration_cast<boost::chrono::duration<long long, boost::ratio<1, 1000000000> >, boost::chrono::duration<long long,
      boost::ratio<1, 1> > >::operator()' requested here
        return boost::chrono::detail::duration_cast<
               ^
/usr/local/include/boost/thread/pthread/timespec.hpp:51:45: note: in instantiation of function template specialization 'boost::chrono::duration_cast<boost::chrono::duration<long long, boost::ratio<1, 1> >, long long, boost::ratio<1,
      1000000000> >' requested here
      ts.tv_sec = static_cast<long>(chrono::duration_cast<chrono::seconds>(ns).count());
                                            ^
In file included from /Users/sbs/projects/osquery/osquery/filesystem/darwin/plist.mm:19:
In file included from /Users/sbs/projects/osquery/include/osquery/logger.h:18:
In file included from /Users/sbs/projects/osquery/include/osquery/database.h:19:
In file included from /Users/sbs/projects/osquery/include/osquery/registry.h:21:
In file included from /Users/sbs/projects/osquery/include/osquery/core.h:17:
In file included from /usr/local/include/boost/thread/shared_mutex.hpp:22:
In file included from /usr/local/include/boost/thread/pthread/shared_mutex.hpp:13:
In file included from /usr/local/include/boost/thread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/pthread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/lock_types.hpp:22:
In file included from /usr/local/include/boost/chrono/time_point.hpp:33:
In file included from /usr/local/include/boost/chrono/duration.hpp:42:
In file included from /usr/local/include/boost/type_traits/common_type.hpp:21:
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:37:1: error: no type named 'type' in 'boost::type_traits_detail::mp_valid_impl<builtin_common_type, long long, long long>'
using mp_valid = typename mp_valid_impl<F, T...>::type;
^~~~~
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:50:95: note: in instantiation of template type alias 'mp_valid' requested here
template<template<class...> class F, class... T> using mp_defer = typename boost::conditional<mp_valid<F, T...>::value, mp_defer_impl<F, T...>, mp_empty>::type;
                                                                                              ^
/usr/local/include/boost/type_traits/common_type.hpp:96:55: note: in instantiation of template type alias 'mp_defer' requested here
template<class T1, class T2> struct common_type_impl: mp_defer<builtin_common_type, T1, T2>
                                                      ^
/usr/local/include/boost/type_traits/common_type.hpp:132:79: note: in instantiation of template class 'boost::type_traits_detail::common_type_impl<long long, long long>' requested here
template<class T1, class T2> struct common_type_decay_helper<T1, T2, T1, T2>: common_type_impl<T1, T2>
                                                                              ^
/usr/local/include/boost/type_traits/common_type.hpp:138:58: note: in instantiation of template class 'boost::type_traits_detail::common_type_decay_helper<long long, long long, long long, long long>' requested here
template<class T1, class T2> struct common_type<T1, T2>: type_traits_detail::common_type_decay_helper<T1, T2>
                                                         ^
/usr/local/include/boost/chrono/duration.hpp:405:37: note: in instantiation of template class 'boost::common_type<long long, long long>' requested here
  typedef chrono::duration<typename common_type<Rep1, Rep2>::type,
                                    ^
/usr/local/include/boost/chrono/duration.hpp:553:14: note: in instantiation of template class 'boost::common_type<boost::chrono::duration<long long, boost::ratio<1, 1000000000> >, boost::chrono::duration<long long, boost::ratio<1, 1> >
      >' requested here
    typename common_type<duration<Rep1, Period1>, duration<Rep2, Period2> >::type
             ^
/usr/local/include/boost/thread/pthread/timespec.hpp:52:42: note: while substituting deduced template arguments into function template 'operator-' [with Rep1 = long long, Period1 = boost::ratio<1, 1000000000>, Rep2 = long long, Period2
      = boost::ratio<1, 1>]
      ts.tv_nsec = static_cast<long>((ns - chrono::duration_cast<chrono::seconds>(ns)).count());
                                         ^
/usr/local/include/boost/thread/pthread/timespec.hpp:52:42: error: invalid operands to binary expression ('const chrono::nanoseconds' (aka 'const duration<boost::int_least64_t, nano>') and 'typename
      boost::enable_if<boost::chrono::detail::is_duration<duration<long long, ratio<1, 1> > >, duration<long long, ratio<1, 1> > >::type' (aka 'boost::chrono::duration<long long, boost::ratio<1, 1> >'))
      ts.tv_nsec = static_cast<long>((ns - chrono::duration_cast<chrono::seconds>(ns)).count());
                                      ~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/chrono/time_point.hpp:272:5: note: candidate template ignored: could not match 'time_point' against 'duration'
    operator-(const time_point<Clock, Duration1>& lhs,
    ^
/usr/local/include/boost/chrono/time_point.hpp:283:5: note: candidate template ignored: could not match 'time_point' against 'duration'
    operator-(const time_point<Clock, Duration1>& lhs,
    ^
/usr/local/include/boost/chrono/duration.hpp:554:5: note: candidate template ignored: substitution failure [with Rep1 = long long, Period1 = boost::ratio<1, 1000000000>, Rep2 = long long, Period2 = boost::ratio<1, 1>]
    operator-(const duration<Rep1, Period1>& lhs,
    ^
/usr/local/include/boost/chrono/duration.hpp:494:19: note: candidate function not viable: requires 0 arguments, but 2 were provided
        duration  operator-() const {return duration(-rep_);}
                  ^
/usr/local/include/boost/chrono/duration.hpp:405:62: error: no type named 'type' in 'boost::common_type<long long, long long>'
  typedef chrono::duration<typename common_type<Rep1, Rep2>::type,
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/usr/local/include/boost/chrono/time_point.hpp:282:14: note: in instantiation of template class 'boost::common_type<boost::chrono::duration<long long, boost::ratio<1, 1000000000> >, boost::chrono::duration<long long, boost::ratio<1,
      1000000000> > >' requested here
    typename common_type<Duration1, Duration2>::type
             ^
/usr/local/include/boost/thread/pthread/condition_variable_fwd.hpp:239:38: note: while substituting deduced template arguments into function template 'operator-' [with Clock = boost::chrono::steady_clock, Duration1 =
      boost::chrono::duration<long long, boost::ratio<1, 1000000000> >, Duration2 = boost::chrono::duration<long long, boost::ratio<1, 1000000000> >]
          return steady_clock::now() - c_now < d ? cv_status::no_timeout :
                                     ^
/usr/local/include/boost/thread/pthread/condition_variable_fwd.hpp:239:38: error: invalid operands to binary expression ('time_point' (aka 'time_point<boost::chrono::steady_clock>') and 'steady_clock::time_point'
      (aka 'time_point<boost::chrono::steady_clock>'))
          return steady_clock::now() - c_now < d ? cv_status::no_timeout :
                 ~~~~~~~~~~~~~~~~~~~ ^ ~~~~~
/usr/local/include/boost/chrono/duration.hpp:554:5: note: candidate template ignored: could not match 'duration' against 'time_point'
    operator-(const duration<Rep1, Period1>& lhs,
    ^
/usr/local/include/boost/chrono/time_point.hpp:272:5: note: candidate template ignored: could not match 'duration' against 'time_point'
    operator-(const time_point<Clock, Duration1>& lhs,
    ^
/usr/local/include/boost/chrono/time_point.hpp:283:5: note: candidate template ignored: substitution failure [with Clock = boost::chrono::steady_clock, Duration1 = boost::chrono::duration<long long, boost::ratio<1, 1000000000> >,
      Duration2 = boost::chrono::duration<long long, boost::ratio<1, 1000000000> >]
    operator-(const time_point<Clock, Duration1>& lhs,
    ^
In file included from /Users/sbs/projects/osquery/osquery/filesystem/darwin/plist.mm:19:
In file included from /Users/sbs/projects/osquery/include/osquery/logger.h:18:
In file included from /Users/sbs/projects/osquery/include/osquery/database.h:19:
In file included from /Users/sbs/projects/osquery/include/osquery/registry.h:21:
In file included from /Users/sbs/projects/osquery/include/osquery/core.h:17:
In file included from /usr/local/include/boost/thread/shared_mutex.hpp:22:
In file included from /usr/local/include/boost/thread/pthread/shared_mutex.hpp:13:
In file included from /usr/local/include/boost/thread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/pthread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/lock_types.hpp:22:
In file included from /usr/local/include/boost/chrono/time_point.hpp:33:
/usr/local/include/boost/chrono/duration.hpp:559:17: error: cannot convert 'const duration<long long, boost::ratio<1, 1000000000> >' to 'CD' (aka 'int') without a conversion operator
      return CD(CD(lhs).count()-CD(rhs).count());
                ^~~~~~
/usr/local/include/boost/chrono/time_point.hpp:286:39: note: in instantiation of function template specialization 'boost::chrono::operator-<long long, boost::ratio<1, 1000000000>, long long, boost::ratio<1, 1000000000> >' requested here
        return lhs.time_since_epoch() - rhs.time_since_epoch();
                                      ^
/usr/local/include/boost/thread/pthread/condition_variable.hpp:279:38: note: in instantiation of function template specialization 'boost::chrono::operator-<boost::chrono::steady_clock, boost::chrono::duration<long long, boost::ratio<1,
      1000000000> >, boost::chrono::duration<long long, boost::ratio<1, 1000000000> > >' requested here
          return steady_clock::now() - c_now < d ? cv_status::no_timeout :
                                     ^
2 warnings and 8 errors generated.
```

### PR DESCRIPTION
**Pull request by sharvilshah**
Boost 1.60.0 with Apple LLVM version 7.0.2 (clang-700.1.81) fails to compile.
The workaround is to disable boost variadic templates.

I couldn't quite get CMake's `CHECK_CXX_SYMBOL_EXISTS` to work, but `find_package` works well.

```
❯ brew info boost
boost: stable 1.60.0 (bottled), HEAD
Collection of portable C++ source libraries
http://www.boost.org
/usr/local/Cellar/boost/1.59.0 (10,928 files, 429.2M)
  Poured from bottle
/usr/local/Cellar/boost/1.60.0 (11,139 files, 436M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/boost.rb

❯ ./build/darwin/osquery/osqueryi "select * from osquery_info"
+-------+-------------------+----------------------------------+--------------+------------+----------------+--------------+------------+
| pid   | version           | config_hash                      | config_valid | extensions | build_platform | build_distro | start_time |
+-------+-------------------+----------------------------------+--------------+------------+----------------+--------------+------------+
| 94510 | 1.6.3-40-g9e4b1cc | e9a961ca5171ddcc829d5098221062d1 | 1            | inactive   | darwin         | 10.11        | 1453322681 |
+-------+-------------------+----------------------------------+--------------+------------+----------------+--------------+------------+
```

Fixes #1782

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...

File: CMakeLists.txt [hunk 1]
```diff
@@ -363,6 +363,14 @@ include_directories("${CMAKE_SOURCE_DIR}")
 include_directories("/usr/local/include")
 link_directories("/usr/local/lib")
 
+# Boost 1.60.0 fails on variadic templates for Apple Clang
+if(APPLE)
```
Comment (theopolis) [inline CMakeLists.txt]: The gate for Apple is because the boost package may not have installed a CMake find package file?

**Comment by theopolis** [comment]
Want to remove the `if(APPLE)` check and apply this to all? Or, can we apply `DBOOST_NO_CXX11_VARIADIC_TEMPLATES` this to all boost versions?

File: CMakeLists.txt (hunk 1 above)
Comment (sharvilshah) [inline CMakeLists.txt]: I think modern-ish CMake installs does have the findBoost file included. I included the Apple check since unlike our Linux provision scripts we can't easily control what version of boost gets installed with `brew`. I can remove that check.

**Comment by sharvilshah** [comment]
I can remove the `Apple` check, and we can apply `DBOOST_NO_CXX11_VARIADIC_TEMPLATES` to all versions.

I did have a few of these warnings:

```
In file included from /usr/local/include/boost/iostreams/detail/resolve.hpp:26:
In file included from /usr/local/include/boost/iostreams/detail/is_dereferenceable.hpp:12:
/usr/local/include/boost/type_traits/detail/bool_trait_def.hpp:18:10: warning: NOTE: Use of this header (bool_trait_def.hpp) is deprecated [-W#pragma-messages]
# pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
```

Not sure if that is because of 1.60.0 or disabling variadic templates.

**Comment by theopolis** [comment]
Yeah, if we drop the conditionals and add the define below: https://github.com/facebook/osquery/pull/1790/files#diff-af3b638bc2a3e6c650974192a53c7291R244 we should be ready to go. I built with 1.59, no deprecation warning and size/speed seems similar.

**Comment by sharvilshah** [comment]
Okay, updated and should be ready for tests.

**Comment by theopolis** [comment]
Can you add this define near:
```
 # Set various platform/platform-version/build version/etc defines.
 add_definitions(
   -DOSQUERY_BUILD_SDK_VERSION=${OSQUERY_BUILD_SDK_VERSION}
   -DOSQUERY_BUILD_PLATFORM=${OSQUERY_BUILD_PLATFORM}
   -DOSQUERY_BUILD_DISTRO=${OSQUERY_BUILD_DISTRO}
   -D${OSQUERY_BUILD_PLATFORM_DEFINE}
   -D${OSQUERY_BUILD_PLATFORM_DEFINE}_${OSQUERY_BUILD_DISTRO_DEFINE}
   -DSTRIP_FLAG_HELP=1
   -DBOOST_NETWORK_ENABLE_HTTPS
 )
```

The [link](https://github.com/facebook/osquery/pull/1790/files#diff-af3b638bc2a3e6c650974192a53c7291R244) included above has the selected line hidden in the Github UI.

**Comment by theopolis** [comment]
ok to test

**Comment by osqueryer** [comment]
Build (ffed82d1e57740ff6ea72a1816d421b03d8a162a) failed :-1:
