### PR TITLE
[Fix #1428] Remove `-mtune` compile flag

### LINKED ISSUE #1428: gflags fails to build on fresh ubuntu14 box
gflags fails to build on vanilla ubuntu14 box on vagrant/virtualbox.

```
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/g++
Build flags: -fPIE;-fPIC;-O2;-DNDEBUG;-march=x86-64;-mtune=i386;-mno-avx
Id flags:

The output was:
1
CMakeCXXCompilerId.cpp:1:0: error: CPU you selected does not support x86-64 instruction set
 /* This source file must have a .cpp extension so that all C++ compilers
 ^


Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /usr/bin/g++
Build flags: -fPIE;-fPIC;-O2;-DNDEBUG;-march=x86-64;-mtune=i386;-mno-avx
Id flags: -c

The output was:
1
CMakeCXXCompilerId.cpp:1:0: error: CPU you selected does not support x86-64 instruction set
```

I did upgrade Vagrant and VirtualBox to the latest releases. VirtualBox 5.0 does support avx instructions, but that shouldn't matter since we have `-mno-avx`

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ cat /proc/cpuinfo | grep flags
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx rdrand lahf_lm abm avx2
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx rdrand lahf_lm abm avx2
```

It does build fine on the centos7.1 box. I did destroy the ubuntu14 box and started again with fresh box but not much help.

### PR DESCRIPTION
**Pull request by sharvilshah**
Having `-mtune=i386` is causing compilation failure for gflags on ubuntu. This change removes the `mtune` compile flag.
`-march` flag is already set to `x86-64` and according to gcc docs:
specifying `-march=cpu-type` implies `-mtune=cpu-type.`

Fixes #1428

The `python_test_release` passes:

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ export RUN_RELEASE_TESTS=1
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ make test
cd build/trusty && cmake ../../ && \
		CTEST_OUTPUT_ON_FAILURE=1 make --no-print-directory test
-- Building for platform Ubuntu (ubuntu, trusty)
-- Building osquery version  1.4.5-401-g1eea02e sdk 1.4.5
-- Configuring done
-- Generating done
-- Build files have been written to: /vagrant/build/trusty
Running tests...
Test project /vagrant/build/trusty
      Start  1: osquery_tests
 1/10 Test  #1: osquery_tests ....................   Passed    0.11 sec
      Start  2: osquery_additional_tests
 2/10 Test  #2: osquery_additional_tests .........   Passed    9.12 sec
      Start  3: osquery_tables_tests
 3/10 Test  #3: osquery_tables_tests .............   Passed    0.04 sec
      Start  4: python_test_osqueryi
 4/10 Test  #4: python_test_osqueryi .............   Passed    6.08 sec
      Start  5: python_test_osqueryd
 5/10 Test  #5: python_test_osqueryd .............   Passed    1.59 sec
      Start  6: python_test_modules
 6/10 Test  #6: python_test_modules ..............   Passed    2.15 sec
      Start  7: python_test_extensions
 7/10 Test  #7: python_test_extensions ...........   Passed    5.76 sec
      Start  8: python_test_additional
 8/10 Test  #8: python_test_additional ...........   Passed    1.18 sec
      Start  9: python_test_example_queries
 9/10 Test  #9: python_test_example_queries ......   Passed    2.74 sec
      Start 10: python_test_release
10/10 Test #10: python_test_release ..............   Passed    3.99 sec

100% tests passed, 0 tests failed out of 10

Total Test time (real) =  32.85 sec
```

### CODE REVIEW

**Comment by osqueryer** [comment]
Can one of the osquery admins reply with "ok to test" to kick off a build...
