### ISSUE TITLE
Breaking changes with Boost 1.60.0

### ISSUE THREAD

**Issue by sharvilshah** [facebook/osquery#1782]
It seems boost 1.60.0 has some breaking changes (might be related to #1781)
Can't build on OS X 10.11 with Apple LLVM version 7.0.2 (clang-700.1.81).

A quick search through Boost's Trac didn't reveal any related bugs, I'll try searching their mailing list.
Builds fine with boost 1.59.0

```
In file included from /usr/local/include/boost/thread/shared_mutex.hpp:22:
In file included from /usr/local/include/boost/thread/pthread/shared_mutex.hpp:13:
In file included from /usr/local/include/boost/thread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/pthread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/lock_types.hpp:22:
In file included from /usr/local/include/boost/chrono/time_point.hpp:33:
In file included from /usr/local/include/boost/chrono/duration.hpp:42:
In file included from /usr/local/include/boost/type_traits/common_type.hpp:21:
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:28:5: warning: declaration does not declare anything [-Wmissing-declarations]
    static boost::true_type check(int);
    ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:31:5: warning: declaration does not declare anything [-Wmissing-declarations]
    static boost::false_type check(...);
    ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:33:27: error: use of undeclared identifier 'check'
    using type = decltype(check<F>(0));
                          ^
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:33:33: error: cannot refer to class template 'F' without a template argument list
    using type = decltype(check<F>(0));
                                ^
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:24:35: note: template is declared here
template<template<class...> class F, class... T>
                                  ^
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:37:1: error: no type named 'type' in 'boost::type_traits_detail::mp_valid_impl<common_type_fold, long long, long long, long>'
using mp_valid = typename mp_valid_impl<F, T...>::type;
^~~~~
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:50:95: note: in instantiation of template type alias 'mp_valid' requested here
template<template<class...> class F, class... T> using mp_defer = typename boost::conditional<mp_valid<F, T...>::value, mp_defer_impl<F, T...>, mp_empty>::type;
                                                                                              ^
/usr/local/include/boost/type_traits/common_type.hpp:47:55: note: in instantiation of template type alias 'mp_defer' requested here
struct common_type<T1, T2, T...>: type_traits_detail::mp_defer<type_traits_detail::common_type_fold, T1, T2, T...>
                                                      ^
/usr/local/include/boost/chrono/duration.hpp:253:30: note: in instantiation of template class 'boost::common_type<long long, long long, long>' requested here
            typedef typename common_type<
                             ^
/usr/local/include/boost/chrono/duration.hpp:315:20: note: in instantiation of member function 'boost::chrono::detail::duration_cast_aux<boost::chrono::duration<long long, boost::ratio<1, 1000000000> >, boost::chrono::duration<long
      long, boost::ratio<1, 1> >, boost::ratio<1, 1000000000>, true, false>::operator()' requested here
            return Aux()(fd);
                   ^
/usr/local/include/boost/chrono/duration.hpp:788:16: note: in instantiation of member function 'boost::chrono::detail::duration_cast<boost::chrono::duration<long long, boost::ratio<1, 1000000000> >, boost::chrono::duration<long long,
      boost::ratio<1, 1> > >::operator()' requested here
        return boost::chrono::detail::duration_cast<
               ^
/usr/local/include/boost/thread/pthread/timespec.hpp:51:45: note: in instantiation of function template specialization 'boost::chrono::duration_cast<boost::chrono::duration<long long, boost::ratio<1, 1> >, long long, boost::ratio<1,
      1000000000> >' requested here
      ts.tv_sec = static_cast<long>(chrono::duration_cast<chrono::seconds>(ns).count());
                                            ^
In file included from /Users/sbs/projects/osquery/osquery/filesystem/darwin/plist.mm:19:
In file included from /Users/sbs/projects/osquery/include/osquery/logger.h:18:
In file included from /Users/sbs/projects/osquery/include/osquery/database.h:19:
In file included from /Users/sbs/projects/osquery/include/osquery/registry.h:21:
In file included from /Users/sbs/projects/osquery/include/osquery/core.h:17:
In file included from /usr/local/include/boost/thread/shared_mutex.hpp:22:
In file included from /usr/local/include/boost/thread/pthread/shared_mutex.hpp:13:
In file included from /usr/local/include/boost/thread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/pthread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/lock_types.hpp:22:
In file included from /usr/local/include/boost/chrono/time_point.hpp:33:
In file included from /usr/local/include/boost/chrono/duration.hpp:42:
In file included from /usr/local/include/boost/type_traits/common_type.hpp:21:
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:37:1: error: no type named 'type' in 'boost::type_traits_detail::mp_valid_impl<builtin_common_type, long long, long long>'
using mp_valid = typename mp_valid_impl<F, T...>::type;
^~~~~
/usr/local/include/boost/type_traits/detail/mp_defer.hpp:50:95: note: in instantiation of template type alias 'mp_valid' requested here
template<template<class...> class F, class... T> using mp_defer = typename boost::conditional<mp_valid<F, T...>::value, mp_defer_impl<F, T...>, mp_empty>::type;
                                                                                              ^
/usr/local/include/boost/type_traits/common_type.hpp:96:55: note: in instantiation of template type alias 'mp_defer' requested here
template<class T1, class T2> struct common_type_impl: mp_defer<builtin_common_type, T1, T2>
                                                      ^
/usr/local/include/boost/type_traits/common_type.hpp:132:79: note: in instantiation of template class 'boost::type_traits_detail::common_type_impl<long long, long long>' requested here
template<class T1, class T2> struct common_type_decay_helper<T1, T2, T1, T2>: common_type_impl<T1, T2>
                                                                              ^
/usr/local/include/boost/type_traits/common_type.hpp:138:58: note: in instantiation of template class 'boost::type_traits_detail::common_type_decay_helper<long long, long long, long long, long long>' requested here
template<class T1, class T2> struct common_type<T1, T2>: type_traits_detail::common_type_decay_helper<T1, T2>
                                                         ^
/usr/local/include/boost/chrono/duration.hpp:405:37: note: in instantiation of template class 'boost::common_type<long long, long long>' requested here
  typedef chrono::duration<typename common_type<Rep1, Rep2>::type,
                                    ^
/usr/local/include/boost/chrono/duration.hpp:553:14: note: in instantiation of template class 'boost::common_type<boost::chrono::duration<long long, boost::ratio<1, 1000000000> >, boost::chrono::duration<long long, boost::ratio<1, 1> >
      >' requested here
    typename common_type<duration<Rep1, Period1>, duration<Rep2, Period2> >::type
             ^
/usr/local/include/boost/thread/pthread/timespec.hpp:52:42: note: while substituting deduced template arguments into function template 'operator-' [with Rep1 = long long, Period1 = boost::ratio<1, 1000000000>, Rep2 = long long, Period2
      = boost::ratio<1, 1>]
      ts.tv_nsec = static_cast<long>((ns - chrono::duration_cast<chrono::seconds>(ns)).count());
                                         ^
/usr/local/include/boost/thread/pthread/timespec.hpp:52:42: error: invalid operands to binary expression ('const chrono::nanoseconds' (aka 'const duration<boost::int_least64_t, nano>') and 'typename
      boost::enable_if<boost::chrono::detail::is_duration<duration<long long, ratio<1, 1> > >, duration<long long, ratio<1, 1> > >::type' (aka 'boost::chrono::duration<long long, boost::ratio<1, 1> >'))
      ts.tv_nsec = static_cast<long>((ns - chrono::duration_cast<chrono::seconds>(ns)).count());
                                      ~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/chrono/time_point.hpp:272:5: note: candidate template ignored: could not match 'time_point' against 'duration'
    operator-(const time_point<Clock, Duration1>& lhs,
    ^
/usr/local/include/boost/chrono/time_point.hpp:283:5: note: candidate template ignored: could not match 'time_point' against 'duration'
    operator-(const time_point<Clock, Duration1>& lhs,
    ^
/usr/local/include/boost/chrono/duration.hpp:554:5: note: candidate template ignored: substitution failure [with Rep1 = long long, Period1 = boost::ratio<1, 1000000000>, Rep2 = long long, Period2 = boost::ratio<1, 1>]
    operator-(const duration<Rep1, Period1>& lhs,
    ^
/usr/local/include/boost/chrono/duration.hpp:494:19: note: candidate function not viable: requires 0 arguments, but 2 were provided
        duration  operator-() const {return duration(-rep_);}
                  ^
/usr/local/include/boost/chrono/duration.hpp:405:62: error: no type named 'type' in 'boost::common_type<long long, long long>'
  typedef chrono::duration<typename common_type<Rep1, Rep2>::type,
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/usr/local/include/boost/chrono/time_point.hpp:282:14: note: in instantiation of template class 'boost::common_type<boost::chrono::duration<long long, boost::ratio<1, 1000000000> >, boost::chrono::duration<long long, boost::ratio<1,
      1000000000> > >' requested here
    typename common_type<Duration1, Duration2>::type
             ^
/usr/local/include/boost/thread/pthread/condition_variable_fwd.hpp:239:38: note: while substituting deduced template arguments into function template 'operator-' [with Clock = boost::chrono::steady_clock, Duration1 =
      boost::chrono::duration<long long, boost::ratio<1, 1000000000> >, Duration2 = boost::chrono::duration<long long, boost::ratio<1, 1000000000> >]
          return steady_clock::now() - c_now < d ? cv_status::no_timeout :
                                     ^
/usr/local/include/boost/thread/pthread/condition_variable_fwd.hpp:239:38: error: invalid operands to binary expression ('time_point' (aka 'time_point<boost::chrono::steady_clock>') and 'steady_clock::time_point'
      (aka 'time_point<boost::chrono::steady_clock>'))
          return steady_clock::now() - c_now < d ? cv_status::no_timeout :
                 ~~~~~~~~~~~~~~~~~~~ ^ ~~~~~
/usr/local/include/boost/chrono/duration.hpp:554:5: note: candidate template ignored: could not match 'duration' against 'time_point'
    operator-(const duration<Rep1, Period1>& lhs,
    ^
/usr/local/include/boost/chrono/time_point.hpp:272:5: note: candidate template ignored: could not match 'duration' against 'time_point'
    operator-(const time_point<Clock, Duration1>& lhs,
    ^
/usr/local/include/boost/chrono/time_point.hpp:283:5: note: candidate template ignored: substitution failure [with Clock = boost::chrono::steady_clock, Duration1 = boost::chrono::duration<long long, boost::ratio<1, 1000000000> >,
      Duration2 = boost::chrono::duration<long long, boost::ratio<1, 1000000000> >]
    operator-(const time_point<Clock, Duration1>& lhs,
    ^
In file included from /Users/sbs/projects/osquery/osquery/filesystem/darwin/plist.mm:19:
In file included from /Users/sbs/projects/osquery/include/osquery/logger.h:18:
In file included from /Users/sbs/projects/osquery/include/osquery/database.h:19:
In file included from /Users/sbs/projects/osquery/include/osquery/registry.h:21:
In file included from /Users/sbs/projects/osquery/include/osquery/core.h:17:
In file included from /usr/local/include/boost/thread/shared_mutex.hpp:22:
In file included from /usr/local/include/boost/thread/pthread/shared_mutex.hpp:13:
In file included from /usr/local/include/boost/thread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/pthread/mutex.hpp:16:
In file included from /usr/local/include/boost/thread/lock_types.hpp:22:
In file included from /usr/local/include/boost/chrono/time_point.hpp:33:
/usr/local/include/boost/chrono/duration.hpp:559:17: error: cannot convert 'const duration<long long, boost::ratio<1, 1000000000> >' to 'CD' (aka 'int') without a conversion operator
      return CD(CD(lhs).count()-CD(rhs).count());
                ^~~~~~
/usr/local/include/boost/chrono/time_point.hpp:286:39: note: in instantiation of function template specialization 'boost::chrono::operator-<long long, boost::ratio<1, 1000000000>, long long, boost::ratio<1, 1000000000> >' requested here
        return lhs.time_since_epoch() - rhs.time_since_epoch();
                                      ^
/usr/local/include/boost/thread/pthread/condition_variable.hpp:279:38: note: in instantiation of function template specialization 'boost::chrono::operator-<boost::chrono::steady_clock, boost::chrono::duration<long long, boost::ratio<1,
      1000000000> >, boost::chrono::duration<long long, boost::ratio<1, 1000000000> > >' requested here
          return steady_clock::now() - c_now < d ? cv_status::no_timeout :
                                     ^
2 warnings and 8 errors generated.
```

**Comment by sharvilshah** [comment]
Found this related bug in Boost's bugtracker: https://svn.boost.org/trac/boost/ticket/11897

It seems to have surfaced a compiler bug in Clang. 
Adding the definition, as was suggested: `BOOST_NO_CXX11_VARIADIC_TEMPLATES` in our cmake file fixes it. I don't want to add a blanket definition, is there a way to grab `BOOST_VERSION` when `find_library` is used?

If not we can mark this as a reference, and wait for clang/boost update that fixes it.

**Comment by theopolis** [comment]
We should attempt to detect the version and add the define if building with 1.60. brew may install the find package script for boost, in which case the version will be easy to find, otherwise we can do some quick symbol resolution and caching.

**Comment by theopolis** [comment]
We can detect this better by having our provision scripts perform a `brew upgrade`. That's a potentially timely event that is best performed async/nightly.

**Comment by sharvilshah** [comment]
I was thinking leveraging `/usr/local/opt/boost/include/boost/version.hpp` since it has both these symbols: `#define BOOST_VERSION 106000` and `#define BOOST_LIB_VERSION "1_60"`

and do something like https://github.com/facebook/osquery/blob/master/CMakeLists.txt#L294-L317
but maybe that's not possible with CMake.
